#size	xhot	yhot	Path to PNG image	delay
24	12	12	sb_h_double_arrow_000.png	50
32	16	15	sb_h_double_arrow_001.png	50
48	24	23	sb_h_double_arrow_002.png	50
64	32	30	sb_h_double_arrow_003.png	50
96	48	45	sb_h_double_arrow_004.png	50
