#size	xhot	yhot	Path to PNG image	delay
24	8	5	pointing_hand_000.png	50
32	10	6	pointing_hand_001.png	50
48	15	9	pointing_hand_002.png	50
64	20	12	pointing_hand_003.png	50
96	30	17	pointing_hand_004.png	50
