#size	xhot	yhot	Path to PNG image	delay
24	4	4	top_left_arrow_000.png	50
32	5	5	top_left_arrow_001.png	50
48	7	7	top_left_arrow_002.png	50
64	9	9	top_left_arrow_003.png	50
96	14	13	top_left_arrow_004.png	50
